package com.lazar.absolutecinema.lexer;

public enum TokenType {
	
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
	LEFT_BRACKET, RIGHT_BRACKET,
	COMMA, DOT, SEMICOLON, COLON,
	AT,

	
	PLUS, PLUS_PLUS, PLUS_EQUAL,
	MINUS, MINUS_MINUS, MINUS_EQUAL,
	STAR, STAR_EQUAL,
	SLASH, SLASH_EQUAL,
	PERCENT, PERCENT_EQUAL,

	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,

	AND_AND, OR_OR,

	
	IDENTIFIER, INT_LITERAL, DOUBLE_LITERAL, STRING_LITERAL, CHAR_LITERAL,

	
	VAR, SCENE, CUT, SCRAP, SETUP, ACTION,
	IF, ELIF, ELSE, KEEP_ROLLING_DURING, KEEP_ROLLING_IF,
	INT, DOUBLE, CHAR, STRING, BOOL, TRUE, FALSE, NULL,

	EOF
}