package com.lazar.core.model;

public enum TokenType {
    /*INT, BEGIN, END, FUNCTION, IF, OR, ELSE, FOR, GOES, FROM, TO, CALL, RETURN,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    ASSIGN,
    NEWLINE, EOF*/

    TYPE_SCRAP, TYPE_INT, TYPE_DOUBLE, TYPE_CHAR, TYPE_STRING, TYPE_SETUP,
    OP_ASSIGN,
    OP_PLUS, OP_MINUS, OP_TIMES, OP_DIVIDE, OP_MODULUS, OP_PLUS_ASSIGN, OP_MINUS_ASSIGN, OP_TIMES_ASSIGN, OP_DIVIDE_ASSIGN, OP_INCREMENT, OP_DECREMENT,
    OP_EQUALS, OP_NOT_EQUALS, OP_LESS_OR_EQUAL, OP_GREATER_OR_EQUAL, OP_LESS, OP_GREATER,
    OP_AND, OP_OR, OP_NOT,
    SCOPE_OPEN_PAREN, SCOPE_CLOSE_PAREN, SCOPE_OPEN_CURLY, SCOPE_CLOSE_CURLY, SCOPE_OPEN_BRACKET, SCOPE_CLOSE_BRACKET,

    LITERAL_INT,
    LITERAL_DOUBLE,
    LITERAL_CHAR,
    LITERAL_STRING,
    LITERAL_IDENTIFIER,

    CONDITIONAL_IF, CONDITIONAL_ELSE, CONDITIONAL_ELSE_IF, CONDITIONAL_KEEP_ROLLING_DURING, CONDITIONAL_KEEP_ROLLING_IF,

    KEYWORD_VAR, KEYWORD_SCENE, KEYWORD_CUT, KEYWORD_ACTION, KEYWORD_SKIP, KEYWORD_EXIT, KEYWORD_ENTRANCE,

    SYMBOL_THIS, SYMBOL_DOUBLE_QUOTE, SYMBOL_QUOTE, SYMBOL_COLON, SYMBOL_SEMICOLON, SYMBOL_COMMA, SYMBOL_DOT, SYMBOL_NEWLINE, SYMBOL_EOF

}
